### ISSUE TITLE
Question about the implementation

### ISSUE THREAD

**Issue by op-rt** [Botffy/polyskel#10]
Hi,

First off, let me thank you for your work on this library. It is rare to find a pure python implementation and I found it very useful.

I am currently working on a simple implementation for [Processing](https://en.wikipedia.org/wiki/Processing_(programming_language)) and am having an issue when computing the bisectors. 

I understand that a bisector at an intersection point is calculated by summing the left edge of the left parent node (A) and the right edge of the right parent node (B).  However, I found that in my case, very often __the new bisector needs to be inverted so the algorithm can keep running without errors.__

A fragment of the `Florida` 's contour you kindly provided:

<img width="745" alt="Annotation 2020-01-26 154525" src="https://user-images.githubusercontent.com/28729303/73136891-02b37500-4053-11ea-8720-f0c5563146df.png">

I got around this problem by inverting all the bisectors that intersects the edge (in blue) between their parent nodes (A and B).

<img width="742" alt="Annotation 2020-01-26 155838" src="https://user-images.githubusercontent.com/28729303/73137062-be28d900-4054-11ea-8492-f6a6ff7cf24d.png">

However, there are cases where that bisector doesn't intersects the edge between its parent nodes but still needs to be inverted:
<img width="696" alt="Annotation 2020-01-26 160550" src="https://user-images.githubusercontent.com/28729303/73137186-c2a1c180-4055-11ea-8200-caa58dafa4ba.png">

Questions: 

- How did you manage all these special cases in your implementation ? 
- Could it be that my bisector function is faulty ?

```
def bisector(p1, p2, p3, p4):
        
        '''Returns a PVector.
           Computes the bisector of a corner between edge p1-p2 and edge p3-p4.'''
        
        dir1 = (p2 - p1).normalize() #direction between 1st point and 2nd point of edge 1
        dir2 = (p4 - p3).normalize() #direction between 1st point and 2nd point of edge 2

        dsum = dir1 + dir2
        vec = PVector(dsum.y, -dsum.x).normalize() 

        return vec 
```

I would really like to have your feedback on this.

Thankfully,

**Comment by Botffy** [comment]
Wow, beautiful images! And sorry about the tardy reply.

There's only one special case, for reflex vertices (that is, vertices the internal angle of which is larger than 180 degrees). Only if a vertex is a reflex vertex we need to invert the calculated bisector.

A bisector is, indeed, calculated by summing the left and right edges. More precisely, given X and left neighbor A and right neighbor B, the bisector is AX + XB. If X is a reflex vertex, the resulting vector must be inverted. X is a reflex vertex if the cross product of AX and XB is negative. 

I implemented it like this:

```
	self._is_reflex = (_cross(*direction_vectors)) < 0
	self._bisector = Ray2(self.point, operator.add(*creator_vectors) * (-1 if self.is_reflex else 1))
```

(...now that I'm look at it, instead of `creator_vectors`, I should probably add the `direction_vectors` in that second line. That'd explain why things get wonky after split events sometimes.)

**Comment by op-rt** [comment]
Hi ! No problem, thank you so much for your reply and explanation, it is very helpful.

There are 2 other cases I would like to have your feedback on (if you don't mind of course).

The first one is **when no pair of rays intersect sooner than either intersects its other neighbor**. 
For example, in the polygon below:

- ray n°2 intersects ray n°3 sooner but...
- ray n°3 intersects ray n°0 sooner but...
- ray n°0 intersects ray n°1 sooner but...
- ray n°1 intersects ray n°2 sooner but... 


![Annotation 2020-02-03 123012](https://user-images.githubusercontent.com/28729303/73651740-5c382700-4685-11ea-918e-e2d0056af7a7.png)

How do you manage this type of situation ?

For now I am forcing the algorithm to have the ray with the smallest intersection distance (ray n°3 in this example) to create a new bisector anyway and it works ok so far.

The second case is **when multiple selected pairs of rays have the same summed distance to their intersection point**.

In the example below the pair formed by ray n°0 and ray n°1 share the same intersection point as the pair formed by ray n°0 and ray n°47. The two pairs have the same summed distance.

![Annotation 2020-02-03 123643](https://user-images.githubusercontent.com/28729303/73652959-6ad40d80-4688-11ea-9855-442b4d8d7eb5.png)

In my implementation, only the first pair in the queue is selected for "reduction" (even if the second pair in the queue have the same summed distance) and this results in the creation of incorrect new bisectors. 

![Annotation 2020-02-03 133811](https://user-images.githubusercontent.com/28729303/73653917-ae2f7b80-468a-11ea-944c-2714fa8e6559.png)

How do you address this case in your implementation ?

**Comment by Botffy** [comment]
Hi!

Case 1: I'm afraid I don't really understand the question. Ray 2 would hit the bisector coming from the reflex vertex nearby on the violet line.

Case2: uhum. At the start of the algorithm, two edge events are generated. One for the bisectors of 0 and 1 meeting, and one for those coming from 0 and 47 meeting. One of them is selected from the priority queue, the new vertex with the weird looking red bisector is created. Let's say it was the event between 0 and 1 as in your example. The vertices 0 and 1 are invalidated. At the next iteration, the edge event of 0 and 47 is selected; but since vertex 0 is already invalidated, the edge event is considered outdated and it's discarded. The algorithm continues as normal. The situation will resolve itself when the LAV that contains the new vertex and 47 "collapses", that is, when it contains only these two vertices, at which point we output the segment connecting them. 

From your questions I sort of think you're not doing the invalidation step, maybe? Are you implementing the algorithm by Felkel and Obdržálek?

**Comment by op-rt** [comment]
Thank you. You are right, I was implementing another logic and ran into way too many special cases that I have decided to do things properly and implement  the algorithm by Felkel and Obdržálek. There are things that are still obscure to me so I may ask questions again later. Hope you won't mind. 

Thanks again.
